version: '3.8'
services:
  web1:
    build: .
    volumes:
      - ./src:/app
    environment:
      SERVER_ID: SERVER-1
    ports:
      - "8001:8000"


  web2:
    build: .
    volumes:
      - ./src:/app
    environment:
      SERVER_ID: SERVER-2
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
