version: '3.8'

services:
  db:
    image: postgres:14.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-q", "-d", "test", "-U", "test" ]
      timeout: 45s
      interval: 10s
      retries: 10

  web1:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql://test:test@db:5432/test
    ports:
      - "8001:8000"

  web2:
    build: .
    depends_on:
      - db
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: postgresql://test:test@db:5432/test
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2

volumes:
  postgres_data:
